#!/bin/bash
#PBS -N fidelity_data
#PBS -j oe
#PBS -o job_outputs/fidelity_data.out
#PBS -e job_outputs/fidelity_data.err
#PBS -lselect=2:ncpus=8:mem=98gb
#PBS -lwalltime=48:00:00

module load anaconda3/personal
module load openfoam/1906
module load intel-suite

cd $PBS_O_WORKDIR
conda env create -f environment.yml 
source activate cfd_optimisation_env
python3 -B multi_fidelity/get_fidelity_quantities.py
