#!/bin/bash
#PBS -N geom
#PBS -j oe
#PBS -o job_outputs/geometry_optimisation.out
#PBS -e job_outputs/geometry_optimisation.err
#PBS -lselect=2:ncpus=8:mem=98gb
#PBS -lwalltime=48:00:00

module load anaconda3/personal
module load openfoam/1906
module load intel-suite

cd $PBS_O_WORKDIR
conda env create -f environment.yml 
source activate cfd_optimisation_env
python3 -B simulation-integration/main_geom.py HPC
