#!/bin/bash
#PBS -N initial_mf_points
#PBS -j oe
#PBS -o outputs/logs/initial_mf_points.out
#PBS -e outputs/logs/initial_mf_points.err
#PBS -lselect=2:ncpus=8:mem=98gb
#PBS -lwalltime=48:00:00

module load anaconda3/personal
module load openfoam/1906
module load intel-suite

cd $PBS_O_WORKDIR
conda env create -f environment.yml 
source activate cfd_optimisation_env
python3 -B simulation-integration/initial_mf_points.py HPC
