#!/bin/bash
#PBS -N validation
#PBS -j oe
#PBS -o outputs/logs/validation.out
#PBS -e outputs/logs/validation.err
#PBS -lselect=2:ncpus=8:mem=98gb
#PBS -lwalltime=48:00:00

module load anaconda3/personal
module load openfoam/1906
module load intel-suite

cd $PBS_O_WORKDIR
conda env create -f environment.yml 
source activate cfd_optimisation_env
python3 -B simulation-integration/mesh_validation.py HPC
